# Generated by Django 3.0.8 on 2021-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('marital', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
